"""Initial database schema

Revision ID: d1316f64dcb1
Revises: 
Create Date: 2026-02-07 04:30:55.636223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1316f64dcb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_model_version'), 'model_registry', ['model_version'], unique=True)
    op.create_table('occupation',
    sa.Column('onet_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_zone', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('onet_code')
    )
    op.create_index(op.f('ix_occupation_onet_code'), 'occupation', ['onet_code'], unique=False)
    op.create_index(op.f('ix_occupation_title'), 'occupation', ['title'], unique=False)
    op.create_table('skill',
    sa.Column('element_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index(op.f('ix_skill_element_id'), 'skill', ['element_id'], unique=False)
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_created_at'), 'user_profile', ['created_at'], unique=False)
    op.create_table('occupation_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('onet_code', sa.String(length=10), nullable=False),
    sa.Column('element_id', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['skill.element_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onet_code'], ['occupation.onet_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onet_code', 'element_id', name='uq_occupation_skill')
    )
    op.create_index('ix_occupation_skill_element_id', 'occupation_skill', ['element_id'], unique=False)
    op.create_index('ix_occupation_skill_onet_code', 'occupation_skill', ['onet_code'], unique=False)
    op.create_table('recommendation_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_onet_code', sa.String(length=10), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_event_created_at', 'recommendation_event', ['created_at'], unique=False)
    op.create_index('ix_recommendation_event_user_id', 'recommendation_event', ['user_id'], unique=False)
    op.create_table('user_current_occupation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('onet_code', sa.String(length=10), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['onet_code'], ['occupation.onet_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_current_occupation_selected_at'), 'user_current_occupation', ['selected_at'], unique=False)
    op.create_index('ix_user_current_occupation_user_id', 'user_current_occupation', ['user_id'], unique=False)
    op.create_table('user_skill_rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=20), nullable=False),
    sa.Column('rating_0_4', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['skill.element_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'element_id', name='uq_user_skill')
    )
    op.create_index('ix_user_skill_rating_user_id', 'user_skill_rating', ['user_id'], unique=False)
    op.create_table('recommended_occupation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('target_onet_code', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.Enum('READY_NOW', 'TRAINABLE', 'LONG_RESKILL', name='recommendationbucket'), nullable=False),
    sa.Column('score_json', sa.JSON(), nullable=False),
    sa.Column('is_exploration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['recommendation_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_onet_code'], ['occupation.onet_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'target_onet_code', name='uq_event_occupation')
    )
    op.create_index(op.f('ix_recommended_occupation_bucket'), 'recommended_occupation', ['bucket'], unique=False)
    op.create_index('ix_recommended_occupation_event_id', 'recommended_occupation', ['event_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('target_onet_code', sa.String(length=10), nullable=False),
    sa.Column('recommended_occupation_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('CLICK', 'SAVE', 'HIDE', 'APPLY', 'INTERVIEW', 'OFFER', name='actiontype'), nullable=False),
    sa.Column('action_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['recommendation_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_occupation_id'], ['recommended_occupation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_feedback_action_at', 'user_feedback', ['action_at'], unique=False)
    op.create_index('ix_user_feedback_action_type', 'user_feedback', ['action_type'], unique=False)
    op.create_index('ix_user_feedback_event_id', 'user_feedback', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_feedback_event_id', table_name='user_feedback')
    op.drop_index('ix_user_feedback_action_type', table_name='user_feedback')
    op.drop_index('ix_user_feedback_action_at', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index('ix_recommended_occupation_event_id', table_name='recommended_occupation')
    op.drop_index(op.f('ix_recommended_occupation_bucket'), table_name='recommended_occupation')
    op.drop_table('recommended_occupation')
    op.drop_index('ix_user_skill_rating_user_id', table_name='user_skill_rating')
    op.drop_table('user_skill_rating')
    op.drop_index('ix_user_current_occupation_user_id', table_name='user_current_occupation')
    op.drop_index(op.f('ix_user_current_occupation_selected_at'), table_name='user_current_occupation')
    op.drop_table('user_current_occupation')
    op.drop_index('ix_recommendation_event_user_id', table_name='recommendation_event')
    op.drop_index('ix_recommendation_event_created_at', table_name='recommendation_event')
    op.drop_table('recommendation_event')
    op.drop_index('ix_occupation_skill_onet_code', table_name='occupation_skill')
    op.drop_index('ix_occupation_skill_element_id', table_name='occupation_skill')
    op.drop_table('occupation_skill')
    op.drop_index(op.f('ix_user_profile_created_at'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_index(op.f('ix_skill_element_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_occupation_title'), table_name='occupation')
    op.drop_index(op.f('ix_occupation_onet_code'), table_name='occupation')
    op.drop_table('occupation')
    op.drop_index(op.f('ix_model_registry_model_version'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
